name: windows_d3d11

on: [push, pull_request]

jobs:
  job_vs2022_d3d11:
    runs-on: [windows-2022]    
    env:
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
   
      - name: Generate project files
        shell: cmd
        run: 'Generate_VS2022_D3D11'
          
      - name: Build
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" /p:Platform=Windows /p:Configuration=Release /m Spartan_d3d11.sln'
          
      - name: Clean up for artifact upload
        shell: bash
        run: ./Scripts/clean.sh d3d11
 
      - uses: actions/upload-artifact@master  
        with:
          name: windows_d3d11
          path: Binaries
